### PR TITLE
update discord.js to v13.7.0

### PR DESCRIPTION
**Pull request by RobertRR11**
Changes between v13.1.0 and v13.7.0 include:
- support for role icons
- support for guild avatars
- support for timeouts
- slash command locales, attachments and modals
- too many bug fixes
- many breaking changes, most being about slash commands

All changes have been tested.

### CODE REVIEW

**Comment by bdotsamir** [comment]
I remember having to make these changes in my own bots. Robert, were the only breaking changes between 13.1 and 13.7 the MessageEmbed#setIcon & setFooter methods? I seem to recall there being something else.

**Comment by RobertRR11** [comment]
There were breaking changes related to slash commands between 13.6 and 13.7, but that's not a problem since the bot doesn't use them yet. I don't know of any other than the ones I've already fixed in this commit. I have also tested the bot after this dependency bump and found no issues.

**Comment by sharkaccino** [comment]
> There were breaking changes related to slash commands between 13.6 and 13.7, but that's not a problem since the bot doesn't use them yet.

uh, do you mean the bot doesn't use anything related to the breaking changes, or that the bot doesn't use slash commands? because if you mean the latter, that's completely false.

https://github.com/JackDotJS/vector-bot/blob/dev/vmodules/events/interaction.js

https://github.com/JackDotJS/vector-bot/tree/dev/vmodules/commands

**Comment by sharkaccino** [comment]
other than that, i see nothing wrong with this pr so i'll go ahead and merge it

**Comment by RobertRR11** [comment]
> uh, do you mean the bot doesn't use anything related to the breaking changes, or that the bot doesn't use slash commands? because if you mean the latter, that's completely false.

didn't notice that, but it looks like it doesn't use anything related to breaking changes

**Pull request merged**
